### PR TITLE
Variables

### PR DESCRIPTION
**Pull request by psiddire**
Refer to the previously closed merge request for changes from that version. The current version incorporates the comments from Jaebak.

### CODE REVIEW

**Comment by jaebak** [comment]
Is Run.sh really needed?

**Comment by jaebak** [comment]
I get a segmentation violation when running the below command with this nano2pico version.

./run/process_nano.exe -f TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISummer16NanoAODv7__PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8_ext1-v1__120000__1E421EBC-226E-DC47-A7CE-BFBCC3760D67.root -i /net/cms17/cms17r0/pico/NanoAODv7/nano/2016/mc -o unit_test_higgsino/mc --nent 100000

**Comment by psiddire** [comment]
> I get a segmentation violation when running the below command with this nano2pico version.

Some of the new variables added are not available in NanoAODv7. Can you try for the same dataset with a NanoAODv9 sample?

**Comment by psiddire** [comment]
> Is Run.sh really needed?

Added it for convenience when testing. Can be removed.

**Comment by jaebak** [comment]
> > I get a segmentation violation when running the below command with this nano2pico version.
> 
> Some of the new variables added are not available in NanoAODv7. Can you try for the same dataset with a NanoAODv9 sample?

Then I think we need to develop a way to prevent this from happening for NanoAODv7 samples. We will probably want to compare with NanoAODv7 samples in the future.

**Comment by psiddire** [comment]
> > > I get a segmentation violation when running the below command with this nano2pico version.
> > 
> > 
> > Some of the new variables added are not available in NanoAODv7. Can you try for the same dataset with a NanoAODv9 sample?
> 
> Then I think we need to develop a way to prevent this from happening for NanoAODv7 samples. We will probably want to compare with NanoAODv7 samples in the future.

I tested a NanoAODv7 sample with the following command:
./run/process_nano.exe -f TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISummer16NanoAODv7__PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8_ext1-v1__120000__1E421EBC-226E-DC47-A7CE-BFBCC3760D67.root -i /net/cms17/cms17r0/pico/NanoAODv7/nano/2016/mc -o unit_test_zgamma --nent 100000

Please note the name of the output directory. It should contain "zgamma". 
So, my previous diagnosis that some of the variables are missing in NanoAODv7 is wrong. It's just that you will need to name the output directory such that it has "zgamma" in it.

**Comment by jaebak** [comment]
> Please note the name of the output directory. It should contain "zgamma". So, my previous diagnosis that some of the variables are missing in NanoAODv7 is wrong. It's just that you will need to name the output directory such that it has "zgamma" in it.

Could you make is so that the crash doesn't happen? For example this same framework is still used for the higgsino analysis, which doesn't have a zgamma in the output directory name.

**Comment by psiddire** [comment]
> > Please note the name of the output directory. It should contain "zgamma". So, my previous diagnosis that some of the variables are missing in NanoAODv7 is wrong. It's just that you will need to name the output directory such that it has "zgamma" in it.
> 
> Could you make is so that the crash doesn't happen? For example this same framework is still used for the higgsino analysis, which doesn't have a zgamma in the output directory name. I mean it doesn't crash before your commit.

I fixed this issue. It was a minor error in the "el_producer" and "mu_producer". It should work now universally for all files. I also removed the "Run.sh" file. I think the pull_request can be merged.

**Comment by jaebak** [comment]
When running the below command

`./run/merge_corrections.exe unit_test_higgsino/mc/corrections/TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISummer16NanoAODv7__PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8_ext1-v1__120000__1E421EBC-226E-DC47-A7CE-BFBCC3760D67.root unit_test_higgsino/mc/wgt_sums/wgt_sums_TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISummer16NanoAODv7__PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8_ext1-v1__120000__1E421EBC-226E-DC47-A7CE-BFBCC3760D67.root`

It is recognized as a 2018 file. The problem is in the `src/merge_corrections.cxx` file at line 59. Could you make this compatible for both UL and non UL?

**Comment by psiddire** [comment]
> When running the below command
> 
> `./run/merge_corrections.exe unit_test_higgsino/mc/corrections/TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISummer16NanoAODv7__PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8_ext1-v1__120000__1E421EBC-226E-DC47-A7CE-BFBCC3760D67.root unit_test_higgsino/mc/wgt_sums/wgt_sums_TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISummer16NanoAODv7__PUMoriond17_Nano02Apr2020_102X_mcRun2_asymptotic_v8_ext1-v1__120000__1E421EBC-226E-DC47-A7CE-BFBCC3760D67.root`
> 
> It is recognized as a 2018 file. The problem is in the `src/merge_corrections.cxx` file at line 59. Could you make this compatible for both UL and non UL?

Thanks for spotting this. I fixed the "merge_corrections.cxx" file.

**Comment by jaebak** [comment]
I was wondering why you removed ll_charge()?

**Comment by psiddire** [comment]
> I was wondering why you removed ll_charge()?

Because of line 33 and 81. Only leptons of opposite charge are considered for dilep_producer. Hence, it will be redundant information to store ll_charge.

**Comment by jaebak** [comment]
I was also wondering how stringent we want to be on the unskimmed picos. For example do we want to put in the if (dimu.M() < 50) cut?

**Comment by jaebak** [comment]
> > I was wondering why you removed ll_charge()?
> 
> Because of line 33 and 81. Only leptons of opposite charge are considered for dilep_producer. Hence, it will be redundant information to store ll_charge.

I guess the question is do we want to be that stringent?

**Comment by psiddire** [comment]
> I was also wondering how stringent we want to be on the unskimmed picos. For example do we want to put in the if (dimu.M() < 50) cut?

I dropped this cut from dilep_producer. Anders was asking me that he wanted to look at events with mll < 50, however, currently they are not stored. 
I still think the opposite sign requirement for the leptons needs to be kept as there is no point in storing dilepton pair information if the pair is not of opposite electric charge.

**Comment by jaebak** [comment]
> I still think the opposite sign requirement for the leptons needs to be kept as there is no point in storing dilepton pair information if the pair is not of opposite electric charge.

The reason why I ask is because I do not know the probability of assigning the charge wrong. Especially for high pT tracks, where + and - tracks could look the same.

**Comment by jaebak** [comment]
> The reason why I ask is because I do not know the probability of assigning the charge wrong. Especially for high pT tracks, where + and - tracks could look the same.

I think we should include dileptons with wrong sign requirements, just in case we need to do some systematic studies related with this.

**Comment by psiddire** [comment]
> The reason why I ask is because I do not know the probability of assigning the charge wrong. Especially for high pT tracks, where + and - tracks could look the same.
I dropped the requirement from the dilep_producer. However, when we run draw pico, we still use "ll_charge == 0". So, if we want to consider wrong charge assignment then that still needs to be considered separately.

**Comment by jaebak** [comment]
https://github.com/psiddire/nano2pico/blob/2be51ca75585a9626a4ac2cf7bc82b6aa7a5a7d1/src/photon_producer.cpp#L92

This has the effect of removing dijet events, because jets that have very poor photons get removed...

**Comment by psiddire** [comment]
> https://github.com/psiddire/nano2pico/blob/2be51ca75585a9626a4ac2cf7bc82b6aa7a5a7d1/src/photon_producer.cpp#L92
> 
> This has the effect of removing dijet events, because jets that have overlap with very poor photons get removed...

Should I replace "isSignal" with "isSig" from line 60?

**Comment by adorsett20** [comment]
Yes, we want nphoton to refer to the number of signal photons. You can rename isSig to isSignal if that is more clear, but the current isSignal should be deleted or renamed (it can be true when the photon is not a signal photon)

**Comment by mcoshiro** [comment]
In the previous commit, I added the Rochester corrections to the muon momentum, but I wonder what do others think about what we should use as default muon pT? Right now, the corrected pts are in a branch called mu_corrected_pt while the default pt is used to calculate ll/llphoton objects.

**Comment by jaebak** [comment]
> In the previous commit, I added the Rochester corrections to the muon momentum, but I wonder what do others think about what we should use as default muon pT? Right now, the corrected pts are in a branch called mu_corrected_pt while the default pt is used to calculate ll/llphoton objects.

I think in the end we will be using the corrected pts, but we will probably want to do some studies (make some plots) with before and after and put it in the AN. For now, I think keeping things simple could help people in learning about the framework.

**Comment by jaebak** [comment]
> In the previous commit, I added the Rochester corrections to the muon momentum, but I wonder what do others think about what we should use as default muon pT? Right now, the corrected pts are in a branch called mu_corrected_pt while the default pt is used to calculate ll/llphoton objects.

I am getting the below error when compiling

inc/RoccoR.hpp:4:10: fatal error: boost/math/special_functions/erf.hpp: No such file or directory
 #include <boost/math/special_functions/erf.hpp>

**Comment by jaebak** [comment]
I will try making a script that finds the cmssw boost library path, where the script can then be used to give the boost path to the compiler.

**Comment by jaebak** [comment]
> I am getting the below error when compiling
> 
> inc/RoccoR.hpp:4:10: fatal error: boost/math/special_functions/erf.hpp: No such file or directory #include <boost/math/special_functions/erf.hpp>

Unfortunately this is not easy to solve.. It seems like cmssw's boost does not have this... The reason why it works on cms37 is because cms37 has a local version of boost installed...
I guess we could compile the boost library and place it in a /net directory that servers can share, although this is adding an extra complexity in using nano2pico.

**Comment by mcoshiro** [comment]
Rather than try to do something complicated with boost, I just switched out the boost functions for the equivalent in ROOT and confirmed that the output numbers were the same.

**Comment by jaebak** [comment]
> Rather than try to do something complicated with boost, I just switched out the boost functions for the equivalent in ROOT and confirmed that the output numbers were the same.

Thanks!

**Comment by jaebak** [comment]
The modification to the cross section code needs to be redone...
For example, for TTJets_SingleLeptFromT higgsino production before w_lumi was 1.82164 and now it is 8.3176...

**Comment by jaebak** [comment]
One thing to note, is that because the 2016 generator is different with the 2017,2018 generator, the partial cross-section can be different because the generators have different kinematic distributions.

**Comment by psiddire** [comment]
I pointed out the GenXsecAnalyzer to Anders. Will work with him to verify the xsec for the ZGamma samples.

**Review by psiddire — COMMENTED** [review]
@Anders Can you remove the kernel folder? I don't think we need it. Also, in mc_producer, line 142 and below the name recoPhoton can still be kept as it is, instead of changing it to compPart.

**Comment by jaebak** [comment]
Here is the log file that has the cross sections that are different: /homes/jbkim/analysis/nano2pico/test_cross_section.log

**Pull request closed without merging**
