### PR TITLE
Sf develop

### PR DESCRIPTION
**Pull request by mcoshiro**
Created PR for changes to add to next production, to be updated as changes are added. So far:

 - Preliminary jet smearing exclusion
 - Fixed sample type bug for run 3 signal
 - Electron 2022(EE) scale/smearing corrections and systematics added
 - Photon 2022(EE) scale/smearing corrections and systematics added
 - JetMET scale/smearing corrections and systematics added, and now cover all eras 2016APV-2023BPix
 - Changed electron IDWP for run 3 and made `el_idLoose` branch refer to it
 - Updated electron ID weights for run 2
 - Updated electron trigger weights for run2
 - Updated muon ID weights, which now cover all eras 2016APV-2023BPix
 - Updated muon trigger weights, which now cover all eras 2016APV-2023BPix
 - Updated photon norm weights, which are now correct for >20 GeV for all eras and <20 GeV for 2023(BPix)
 - Added btag weights, which now cover all eras 2016APV-2023BPix
 - Made scale/smear (Rochester) corrected muon pt default (NOTE: this affects things downstream like kinematic refit)

### CODE REVIEW

**Review by jdgrassi — COMMENTED** [review]
Few small things, but otherwise looks good. I did not really view any details on the JSONs so I'll have to assume they're fine :)

**Review by andersbarzdukas — COMMENTED** [review]
Do we want to not apply smearing to only events in this range or to non-truth matched particles generally. I think the effect is the same generally, but I just wanted to check

**Comment by mcoshiro** [comment]
I would definitely want to apply smearing to non-truth matched jets where MC isn't doing something strange, such as for regular jets in the region with tracker coverage |η|~<2.4. Whether we want to do just 2.5<|η|<3.0 or have a larger/smaller range, I am not sure.

**Comment by andersbarzdukas** [comment]
> I would definitely want to apply smearing to non-truth matched jets where MC isn't doing something strange, such as for regular jets in the region with tracker coverage |η|~<2.4. Whether we want to do just 2.5<|η|<3.0 or have a larger/smaller range, I am not sure.

I think 2.5 < eta< 3.0 is good then. The code looked good to me. I am just trying to make the test picos and have been running into issues unrelated to nano2pico. I will send another message after I check the unit test picos

**Comment by andersbarzdukas** [comment]
Looking over the test picos everything seem to look good. I am not sure if this is just very low stats, but w_photon seemed a little jagged in 2022EE ggF pico from test sample (attached plot). This is likely a non-issue, but just wanted to run it by others. 
w_photon_ggF_2022EE

**Comment by mcoshiro** [comment]
> Looking over the test picos everything seem to look good. I am not sure if this is just very low stats, but w_photon seemed a little jagged in 2022EE ggF pico from test sample (attached plot). This is likely a non-issue, but just wanted to run it by others. w_photon_ggF_2022EE

Yeah, I think as you say this is a non-issue. The weights themselves are discrete at some level since they just come from an eta-pt binning. I think you may have also gotten unlucky with the considered events, with a slightly larger sample, here is distribution I get (big spike at ~1 from events with no photons in acceptance for reweighting)
hzg_wphoton

**Pull request merged**
